// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalManagementSystem.Data;

#nullable disable

namespace RentalManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20240806131107_addmodelsToDb")]
    partial class addmodelsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalManagementSystem.Models.Bookings.Bookings", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("TenantTenatId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("TenantTenatId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("RentalManagementSystem.Models.Rooms.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("BookingsBookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Deposit")
                        .HasColumnType("float");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<double>("RentCost")
                        .HasColumnType("float");

                    b.Property<string>("RoomCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("RoomId");

                    b.HasIndex("BookingsBookingId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("RentalManagementSystem.Models.Tenants.Occupant", b =>
                {
                    b.Property<int>("TenatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenatId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idno")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenatId");

                    b.ToTable("Occupant");
                });

            modelBuilder.Entity("RentalManagementSystem.Models.Bookings.Bookings", b =>
                {
                    b.HasOne("RentalManagementSystem.Models.Tenants.Occupant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantTenatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalManagementSystem.Models.Rooms.Room", b =>
                {
                    b.HasOne("RentalManagementSystem.Models.Bookings.Bookings", null)
                        .WithMany("Room")
                        .HasForeignKey("BookingsBookingId");
                });

            modelBuilder.Entity("RentalManagementSystem.Models.Bookings.Bookings", b =>
                {
                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
